假设我们相对函数 $y=2x^{T}x $ 关于向量x求导 

In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad #默认是None

In [5]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4*x

tensor([True, True, True, True])

默认情况下，Pytorch会累积提督，我们需要清楚之前的值

In [9]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
x.grad.zero_()
y = x*x
u = y.detach() #把y当作一个常数，值为x*x
z = u*x
z.sum().backward()
x.grad , x.grad == u

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))

In [13]:
x.grad.zero_()
y.sum().backward()
x.grad , x.grad == 2*x

(tensor([0., 2., 4., 6.]), tensor([True, True, True, True]))

In [16]:
def f(a):
    b = 2*a
    while b.norm()<1000:
        b = b*2
    if b.sum()>0:
        c = b
    else:
        c = 100*b
    return c

a = torch.rand(size=(),requires_grad=True) #size=()表示a是标量
d = f(a)
d.backward()

# 不管走那个分支都会得出 d = n*a
a.grad == d/a 

tensor(True)