In [1]:
import torch
x = torch.arange(24).reshape(2,3,4)
x


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [2]:
x.sum(),x.shape

(tensor(276), torch.Size([2, 3, 4]))

In [3]:
x_sum_axis0 = x.sum(axis=0)
x_sum_axis0,x_sum_axis0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [4]:
x_sum_axis0 = x.sum(axis=1)
x_sum_axis0,x_sum_axis0.shape

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [5]:
x_sum_axis0 = x.sum(axis=2)
x_sum_axis0,x_sum_axis0.shape

(tensor([[ 6, 22, 38],
         [54, 70, 86]]),
 torch.Size([2, 3]))

In [6]:
x_sum_axis0 = x.sum(axis=[0,1])
x_sum_axis0,x_sum_axis0.shape

(tensor([60, 66, 72, 78]), torch.Size([4]))

计算总和或举止保持轴数量不变

In [7]:
sum_x = x.sum(axis=0,keepdims=True)
sum_x , sum_x.shape

(tensor([[[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]),
 torch.Size([1, 3, 4]))

这样维度不会丢掉，可以利用广播机制计算x/sum_x

In [8]:
x/sum_x

tensor([[[0.0000, 0.0714, 0.1250, 0.1667],
         [0.2000, 0.2273, 0.2500, 0.2692],
         [0.2857, 0.3000, 0.3125, 0.3235]],

        [[1.0000, 0.9286, 0.8750, 0.8333],
         [0.8000, 0.7727, 0.7500, 0.7308],
         [0.7143, 0.7000, 0.6875, 0.6765]]])

x,y都是向量的话，可以进行点积（按元素乘积后求和）和乘积

In [9]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x,y,x*y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor([0., 1., 2., 3.]),
 tensor(6.))

矩阵向量相乘

In [10]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵之间相乘

In [11]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根

In [12]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数是向量元素绝对值之和

In [13]:
torch.abs(u).sum()

tensor(7.)

矩阵的弗洛贝尼斯范数（Frobenius norm）是矩阵元素的平方和的平方根

In [14]:
torch.norm(torch.ones((4,9)))

tensor(6.)