In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import mglearn

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
from sklearn.datasets import load_digits

digits = load_digits()
print(digits.target)
y = digits.target==9
print(y)

[0 1 2 ... 8 9 8]
[False False False ... False  True False]


In [3]:
print(digits.data[1])

[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
bards_words =["The fool doth think he is wise,","but the wise man knows himself to be a fool","i am no a fool","but who is the fool","i am not you"]
vect = CountVectorizer()
vect.fit(bards_words)
bag_of_words = vect.transform(bards_words)
print(bag_of_words)


  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 12)	1
  (0, 13)	1
  (0, 16)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (1, 6)	1
  (1, 8)	1
  (1, 9)	1
  (1, 12)	1
  (1, 14)	1
  (1, 16)	1
  (2, 0)	1
  (2, 4)	1
  (2, 10)	1
  (3, 2)	1
  (3, 4)	1
  (3, 7)	1
  (3, 12)	1
  (3, 15)	1
  (4, 0)	1
  (4, 11)	1
  (4, 17)	1


In [5]:
print(bag_of_words.toarray())

[[0 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 1 0]
 [0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 0]
 [1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]]


In [6]:
print('the first line is \n{}'.format(bag_of_words[0]))
print('the second line is \n{}'.format(bag_of_words[1]))

the first line is 
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 12)	1
  (0, 13)	1
  (0, 16)	1
the second line is 
  (0, 1)	1
  (0, 2)	1
  (0, 4)	1
  (0, 6)	1
  (0, 8)	1
  (0, 9)	1
  (0, 12)	1
  (0, 14)	1
  (0, 16)	1


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidf = TfidfVectorizer()
tfidf.fit(bards_words)

TfidfVectorizer()

In [8]:
x_tfidf = tfidf.transform(bards_words)
print(x_tfidf)

  (0, 16)	0.3583893457792225
  (0, 13)	0.44421435644553064
  (0, 12)	0.29749553163111786
  (0, 7)	0.3583893457792225
  (0, 5)	0.44421435644553064
  (0, 4)	0.2502626198745013
  (0, 3)	0.44421435644553064
  (1, 16)	0.3034743854506345
  (1, 14)	0.3761486785762367
  (1, 12)	0.25191115388703433
  (1, 9)	0.3761486785762367
  (1, 8)	0.3761486785762367
  (1, 6)	0.3761486785762367
  (1, 4)	0.21191560425031786
  (1, 2)	0.3034743854506345
  (1, 1)	0.3761486785762367
  (2, 10)	0.7127752157729959
  (2, 4)	0.4015651234424611
  (2, 0)	0.5750625560879445
  (3, 15)	0.5709397983956458
  (3, 12)	0.38236503703342845
  (3, 7)	0.46063063441630786
  (3, 4)	0.32165752336425085
  (3, 2)	0.46063063441630786
  (4, 17)	0.6141889663426562
  (4, 11)	0.6141889663426562
  (4, 0)	0.49552379079705033


In [9]:
print(x_tfidf.max(axis=0))
print(x_tfidf.max(axis=0).toarray())
print(x_tfidf.max(axis=0).toarray().ravel())

  (0, 0)	0.5750625560879445
  (0, 1)	0.3761486785762367
  (0, 2)	0.46063063441630786
  (0, 3)	0.44421435644553064
  (0, 4)	0.4015651234424611
  (0, 5)	0.44421435644553064
  (0, 6)	0.3761486785762367
  (0, 7)	0.46063063441630786
  (0, 8)	0.3761486785762367
  (0, 9)	0.3761486785762367
  (0, 10)	0.7127752157729959
  (0, 11)	0.6141889663426562
  (0, 12)	0.38236503703342845
  (0, 13)	0.44421435644553064
  (0, 14)	0.3761486785762367
  (0, 15)	0.5709397983956458
  (0, 16)	0.3583893457792225
  (0, 17)	0.6141889663426562
[[0.57506256 0.37614868 0.46063063 0.44421436 0.40156512 0.44421436
  0.37614868 0.46063063 0.37614868 0.37614868 0.71277522 0.61418897
  0.38236504 0.44421436 0.37614868 0.5709398  0.35838935 0.61418897]]
[0.57506256 0.37614868 0.46063063 0.44421436 0.40156512 0.44421436
 0.37614868 0.46063063 0.37614868 0.37614868 0.71277522 0.61418897
 0.38236504 0.44421436 0.37614868 0.5709398  0.35838935 0.61418897]


In [12]:
print(tfidf.get_feature_names())

['am', 'be', 'but', 'doth', 'fool', 'he', 'himself', 'is', 'knows', 'man', 'no', 'not', 'the', 'think', 'to', 'who', 'wise', 'you']


In [1]:
python3 -m spacy download en

SyntaxError: invalid syntax (<ipython-input-1-a2972acdc524>, line 1)